// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcTcBm0lkqPIrQmFaTgjktkHLpGhY9raE',
    appId: '1:181611573156:web:26f15dfaf04de58dc5db31',
    messagingSenderId: '181611573156',
    projectId: 'travel-app-agent-71f71',
    authDomain: 'travel-app-agent-71f71.firebaseapp.com',
    storageBucket: 'travel-app-agent-71f71.firebasestorage.app',
    measurementId: 'G-ET3FWTQR2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB54JHoTIL_8l3FUH0meqCmggRlAAqwRKU',
    appId: '1:181611573156:android:34e5c6dc08bc2d41c5db31',
    messagingSenderId: '181611573156',
    projectId: 'travel-app-agent-71f71',
    storageBucket: 'travel-app-agent-71f71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3L2qNbfW4GdjHIH58krBD2yVZbD0S36s',
    appId: '1:181611573156:ios:4c48ced287989a3ec5db31',
    messagingSenderId: '181611573156',
    projectId: 'travel-app-agent-71f71',
    storageBucket: 'travel-app-agent-71f71.firebasestorage.app',
    iosBundleId: 'com.example.travelAppGdg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3L2qNbfW4GdjHIH58krBD2yVZbD0S36s',
    appId: '1:181611573156:ios:4c48ced287989a3ec5db31',
    messagingSenderId: '181611573156',
    projectId: 'travel-app-agent-71f71',
    storageBucket: 'travel-app-agent-71f71.firebasestorage.app',
    iosBundleId: 'com.example.travelAppGdg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcTcBm0lkqPIrQmFaTgjktkHLpGhY9raE',
    appId: '1:181611573156:web:ce865f06e67cb82fc5db31',
    messagingSenderId: '181611573156',
    projectId: 'travel-app-agent-71f71',
    authDomain: 'travel-app-agent-71f71.firebaseapp.com',
    storageBucket: 'travel-app-agent-71f71.firebasestorage.app',
    measurementId: 'G-66GMMD1CLB',
  );
}
